[theme]
theme = "dracula"
[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 1
format = " $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon RTX 3080Ti $utilization $temperature $clocks "

[[block]]
block = "github"
token = ""
format = " $icon $total.eng(w:1) "
info = ["total"]
warning = ["mention","review_requested"]
hide_if_total_is_zero = false

[[block]]
block = "load"
format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1

[[block]]
block = "disk_space"
path = "/run/media/valery/backups"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon backups: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/run/media/valery/data"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon data: $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon main: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "docker"
interval = 2
format = " $icon $running/$total "

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
