[theme]
theme = "native"
[icons]
icons = "awesome6"

[[block]]
block = "music"
format = "$combo.str(20) $prev $play $next|"
player = "spotify"

[[block]]
block = "github"
format = "$total.eng(1)|$mention.eng(1)"
interval = 60
token = ""

[[block]]
block = "disk_space"
info_type = "available"
path = "/"
alert_unit = "GB"
alert = 100.0
warning = 300.0
format = "$available.eng(4)"

[[block]]
block = "docker"
interval = 2
format = "$running/$total"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "$mem_total_used_percents.eng(2)"
format_swap = "$swap_used_percents.eng(2)"

[[block]]
block = "nvidia_gpu"
interval = 1
format = "GPU l:$utilization t:$temperature c:$clocks"

[[block]]
interval = 1
block = "net"
format = "{$signal_strength $ssid $frequency|Wired connection} via $device $speed_up $speed_down"

[[block]]
block = "cpu"
interval = 1
format = "$barchart.str() $utilization.eng()"
format_alt = "$frequency.eng() \\|$boost.str()"

[[block]]
block = "temperature"
format = "$min min, $max max, $average avg|"
interval = 1
chip = "coretemp-isa-0000"

[[block]]
block = "load"
interval = 1

[[block]]
block = "sound"
format = "{ $volume|}"

[[block]]
block = "keyboard_layout"
driver = "kbddbus"
[block.mappings]
"Polish" = "pl"

[[block]]
block = "time"
interval = 1
locale = "pl_PL"
format = "%a %d/%m %R"
