[docker_context]
format = "via [🐋 $context](blue bold)"

[git_branch]
symbol = "🌱 "
truncation_length = 50
truncation_symbol = "..."

[git_commit]
commit_hash_length = 50
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 "
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](green)'
renamed = "👅"

[golang]
format = "via [🏎💨 $version](bold cyan) "


[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = "48d90782"
disabled = false

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"

[rust]
format = "via [⚙️  $version ](red bold)"

[status]
style = "bg:blue"
symbol = "💣 "
format = '[\[$symbol$status\]]($style) '
disabled = false

[time]
disabled = false
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"


